# Generated by Django 5.2.17 on 2026-09-27 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('population', models.IntegerField(default=0)),
                ('hazard_score', models.FloatField(default=0)),
                ('vulnerability_score', models.FloatField(default=0)),
                ('hazard_level', models.CharField(choices=[('SAFE', 'Safe'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('RED', 'Red Zone')], default='SAFE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('available_area_hectares', models.FloatField()),
                ('estimated_capacity', models.IntegerField()),
                ('current_occupied', models.IntegerField(default=0)),
                ('hazard_score', models.FloatField(default=0)),
                ('road_access', models.BooleanField(default=True)),
                ('water_availability', models.BooleanField(default=True)),
            ],
        ),
    ]
