# Generated by Django 5.2.17 on 2026-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitation',
            name='avg_annual_rainfall_mm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='distance_to_coast_km',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='distance_to_river_km',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='elevation_m',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='habitation',
            name='extreme_rainfall_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='pct_dilapidated_housing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='pct_kutcha_roof_wall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='pct_no_drainage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='pct_no_drinking_water_premises',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='pct_no_toilet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='habitation',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitation',
            name='seismic_zone',
            field=models.CharField(choices=[('II', 'Zone II (Low)'), ('III', 'Zone III (Moderate)'), ('IV', 'Zone IV (High)'), ('V', 'Zone V (Very High)')], default='III', max_length=5),
        ),
    ]
